### ISSUE TITLE
Deploy minimal public Quetz instance

### ISSUE THREAD

**Issue by jaimergp** [Quansight-Labs/czi-conda-forge-mgmt#15]
## 📌 Summary

Deploy a minimal Quetz instance for conda-forge and bioconda

## 📝 Background

[Quetz](https://github.com/mamba-org/quetz) is an open-source server for conda packages and channel metadata.
Its UI frontend can be extended with components.

The idea is to have a running instance that the team can use to iterate on the planned features and receive feedback from the community.

## 🚀 Tasks / Deliverables

- [ ] Decide hosting / domain / infra details
- [ ] Configure vanilla Quetz server and put it online
- [ ] Devise workflow to make the new features available in the preview

## 📅 Estimated completion

This task should be finished in the first [six months](https://github.com/Quansight-Labs/czi-conda-forge-mgmt/milestone/1).

## ℹ️ References

- [Quetz](https://github.com/mamba-org/quetz)
- [beta.mamba.pm](https://beta.mamba.pm/): A running instance of Quetz
- [prefix.dev](https://prefix.dev/): Another server with information about conda channels

**Comment by jaimergp** [comment]
We have decided not to go ahead with a Quetz instance. The question of infra costs (i.e. billing), setup and ongoing maintenance is not clear. We have decided to instead rely on smaller components that target specific needs individually:

- Metadata consultation: https://conda-metadata-app.streamlit.app/
- conda-forge status: https://conda-forge.org/status
- Package to feedstock mapping: https://conda-forge.org/packages

There other projects in the ecosystems with similar functionality, namely:

- https://beta.mamba.pm/channels/conda-forge
- https://prefix.dev/channels/conda-forge
- https://anaconda.org/conda-forge
