### ISSUE TITLE
Audit of the current infrastructure, tooling, and credentials

### ISSUE THREAD

**Issue by jaimergp** [Quansight-Labs/czi-conda-forge-mgmt#2]
## 📌 Summary

The goal is to audit and document existing conda-forge's infrastructure.

> This will be done in public.
> We need to ensure no critical security details such as credentials are exposed.

## 📝 Background

To propose technical debt reduction measures and ensure the long-term viability of the project and its growing ecosystem, we first need to understand and document the current status of the platform.

Expected challenges:

- Large number of moving parts across services and platforms
- Several accounts and credentials key to the normal operating conditions
- Lack of documentation for each part
- Scattered institutional knowledge

```[tasklist]
### 🚀 Tasks / Deliverables
- [x] #27
- [x] RST to MD in Docusaurus, permanently, with git history preservation if possible: https://github.com/conda-forge/conda-forge.github.io/pull/2084
- [ ] #31
- [ ] https://github.com/Quansight-Labs/czi-conda-forge-mgmt/issues/55
- [ ] #37
- [ ] https://github.com/Quansight-Labs/czi-conda-forge-mgmt/issues/42
- [ ] https://github.com/Quansight-Labs/czi-conda-forge-mgmt/issues/3
- [ ] https://github.com/Quansight-Labs/czi-conda-forge-mgmt/issues/56
```

## 📅 Estimated completion

This task should be finished in the first [six months](https://github.com/Quansight-Labs/czi-conda-forge-mgmt/milestone/1).

## ℹ️ References

- [conda-forge's Security and Systems Sub-Team](https://conda-forge.org/docs/orga/subteams.html#security-and-systems-sub-team)
- [conda-forge's Bot Sub-Team](https://conda-forge.org/docs/orga/subteams.html#bot-sub-team)
- [conda-forge repositories that are not regular feedstocks](https://hackmd.io/nlD1rNVzQ-iA2B6o2mLWRA)
- [`regro/cf-scripts` documentation](https://regro.github.io/cf-scripts/)
- [Talks about conda-forge](https://conda-forge.org/docs/user/talks.html) (some cover infrastructure)
- [regro.github.io](https://regro.github.io/)
