### ISSUE TITLE
Thorough documentation for maintainers dashboard

### ISSUE THREAD

**Issue by jaimergp** [Quansight-Labs/czi-conda-forge-mgmt#20]
## 📌 Summary

Develop end-user and maintainer documentation as needed, including security best practices for supply chain security and Quetz dashboard use.

## 📝 Background

At this point, a Quetz instance providing services for conda-forge and bioconda should be ready and running.

To ensure its long-term sustainability, thorough documentation should be available, covering user- and developer-focused topics.

## 🚀 Tasks / Deliverables

- [ ] How to access and use, recommended workflows, tips and tricks
- [ ] How to contribute: how the source code is structured, code style, etc
- [ ] How to deploy your own instance

## 📅 Estimated completion

This task should be done by the end of the project ([24 months](https://github.com/Quansight-Labs/czi-conda-forge-mgmt/milestone/4)).

## ℹ️ References

- [Quetz documentation](https://quetz.readthedocs.io)
