### ISSUE TITLE
Run a scalable mirror of conda-forge on GitHub packages.

### ISSUE THREAD

**Issue by jaimergp** [Quansight-Labs/czi-conda-forge-mgmt#23]
## 📌 Summary

Create and maintain a mirror of conda-forge and bioconda on Github packages

## 📝 Background

Using the OCI capabilities of Github Packages, we can store conda artifacts.
This can be used as a mirror for archival purposes, at the very least.

```[tasklist]
## 🚀 Tasks / Deliverables
- [ ] https://github.com/conda/ceps/pull/70
- [ ] Staging mechanism
- [ ] Repodata indexing mechanism
- [ ] https://github.com/channel-mirrors/mirrormirror/issues/11
- [ ] https://github.com/channel-mirrors/mirrormirror/issues/12
- [ ] https://github.com/channel-mirrors/mirrormirror/issues/13
```

## 📅 Estimated completion

This task should be finished in the first [12 months](https://github.com/Quansight-Labs/czi-conda-forge-mgmt/milestone/2).

## ℹ️ References

- [Initial prototype](https://github.com/channel-mirrors)
- [Github Action to run the sync](https://github.com/regro/cf-oci-mirror-action)
- https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/208

**Comment by jaimergp** [comment]
About direct uploads to `ghcr.io`, see [this document](https://docs.google.com/document/d/1wFXIUeFN803TcVxN2CynII4jmko2lnFzssGuDaDHhkA/edit).

**Comment by jaimergp** [comment]
xref https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/208

**Comment by jaimergp** [comment]
Important CEP: https://github.com/conda-incubator/ceps/blob/main/cep-15.md

This allows the repodata and packages to live in separate locations.

**Comment by jaimergp** [comment]
I recently fixed the mirroring action, which had been failing for some months due to the repo being inactive. The keep-alive action was also broken which led to inactive keep-alives. It's working now: https://github.com/channel-mirrors/mirrormirror/actions

The osx-64 errors are caused by this ongoing issue with some artifacts not being CDN'd on Anaconda's side, but not critical to the rest of the files in the mirror.

- See https://github.com/conda/infrastructure/issues/797

There are some extra [errors](https://github.com/channel-mirrors/mirrormirror/actions/runs/8064834160) in osx-arm64 and bioconda caused by connection errors of different types. @goanpeca can you look into this?
