### ISSUE TITLE
Add OCI registry support in conda/mamba

### ISSUE THREAD

**Issue by jaimergp** [Quansight-Labs/czi-conda-forge-mgmt#24]
## 📌 Summary

Make `conda` and `mamba` support OCI registries as repodata and packages sources.

## 📝 Background

Having an OCI mirror is only the archival part.
The tooling has to learn how to "speak" to it.

`conda` and `mamba` should be able to download repodata and packages from OCI-backed servers.

```[tasklist]
### 🚀 Tasks / Deliverables
- [ ] Add support for OCI servers on `conda`
- [x] Add support for OCI servers on `libmamba` (expected in v2): https://github.com/mamba-org/mamba/pull/2795 https://github.com/mamba-org/mamba/pull/3125 https://github.com/mamba-org/mamba/pull/3178 https://github.com/mamba-org/mamba/releases/tag/libmamba-2.0.0alpha4
- [ ] https://github.com/conda-incubator/ceps/pull/70
```

## ℹ️ References

- [`conda/conda`](https://github.com/conda/conda)
- [`mamba-org/mamba`](https://github.com/mamba-org/mamba)
- [`mamba-org/powerloader`](https://github.com/mamba-org/powerloader)
