### ISSUE TITLE
Access control: on- and off-boarding core members

### ISSUE THREAD

**Issue by jaimergp** [Quansight-Labs/czi-conda-forge-mgmt#3]
## 📌 Summary

Document the onboarding and off-boarding process, with the aim of eventually automating most steps.

## 📝 Background

When a user joins any of the conda-forge teams, members of the core team need to manually provision the permissions across the required services.
The list of services and the required permissions are not fully enumerated,
and members sometimes acquire the needed credentials by manually requesting it to other members, as needed.

This also means there's no comprehensive list or way of knowing who has access to each service.

## 🚀 Tasks / Deliverables

```[tasklist]
- [ ] https://github.com/Quansight-Labs/czi-conda-forge-mgmt/issues/61
- [x] Added a PR to document onboarding and offboarding.
- [x] Automate provisioning as much as possible
- [X] https://github.com/conda-forge/admin-requests/pull/904
- [X] https://github.com/conda-forge/admin-requests/pull/906 
```

## 📅 Estimated completion

This task should be finished in the first [six months](https://github.com/Quansight-Labs/czi-conda-forge-mgmt/milestone/1).

## ℹ️ References

- ...
- ...
- ...

**Comment by jaimergp** [comment]
Pending: Consult conda-forge core team whether they want this information (already written) published in the website or internally.

**Comment by jaimergp** [comment]
Only https://github.com/Quansight-Labs/czi-conda-forge-mgmt/issues/61 left. Closing this one.
