### ISSUE TITLE
ENH - Project management

### ISSUE THREAD

**Issue by trallard** [Quansight-Labs/czi-conda-forge-mgmt#30]
## TODO

- [ ] Add workflows for:
  - [ ] Adding issues/PRs to the project board
  - [ ] Automated report (internal reporting)
