### ISSUE TITLE
Design and implement a database for the conda-forge graph and relevant metadata

### ISSUE THREAD

**Issue by jaimergp** [Quansight-Labs/czi-conda-forge-mgmt#5]
## 📌 Summary

Migration of existing data sources into a purpose-built database, including a suitable
data schema and schema validation.

## 📝 Background

The metadata supporting the diverse automations at conda-forge is made of a number of repositories that serve JSON files in a given directory structure.

Depending on the tool, the metadata will be used to build a graph.
This data is downloaded, and the graph recreated, every time the job runs, adding to substantial overhead as conda-forge grows.

Other tools depend on a different presentation of the metadata, and are supported a different repository.
This means that the same data is duplicated just to be presented in a different way.

This is not sustainable or considerate with the available resources, and we would prefer a single source of truth that runs in a performant way.

## 🚀 Tasks / Deliverables

- [X] Enumerate data sources and their intended usage
  - `regro/cf-graph-countyfair`: maintained and used by `regro/cf-scripts`  (autotick bot). Also powers the status page and other things.
  - `regro/libcfgraph`: maintained by `regro/libcflib` and used by several pieces. Most important pieces: `run_exports` data and the import maps.
  - `conda-forge/feedstock-outputs`: maps package names to feedstocks that are allowed to generate them.
  - `conda-forge/artifact-validation`: map of file paths to originating artifacts. Currently not available in a global way, only for some special packages.
- [ ] Provide alternative sources for some metadata
  - [x] `libcfgraph`'s `artifacts/` can be fetched from GHCR OCI mirror: https://github.com/regro/conda-forge-metadata/pull/6
    - [x] Needs https://github.com/conda-forge/staged-recipes/pull/22555
      - [X] Needs a new release: https://github.com/channel-mirrors/conda-oci-mirror/releases/tag/v0.1.0
        - [X] Needs https://github.com/channel-mirrors/conda-oci-mirror/pull/27
    - [X] Provide a web frontend for this backend: https://conda-metadata-app.streamlit.app/
       - [ ] Link to backend from conda-forge.org/packages?
  - [x] `feedstock-outputs`: https://github.com/regro/conda-forge-metadata/pull/7
    - [x] Needs https://github.com/conda-forge/feedstock-outputs/pull/44
    - [x] Enables:
      - [x] https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/233
      - [x] https://github.com/conda-forge/conda-forge-webservices/pull/552
  - [x] Investigate if `run_exports` can be served next to `repodata.json` files: 
    - [x] https://github.com/conda-incubator/ceps/pull/51
      - [x] https://github.com/conda/schemas/pull/25
      - [x] https://github.com/conda/conda-index/pull/110
      - [X] Have Anaconda.org enable `--run-exports` and serve those files ([example `run_exports.json`](https://conda.anaconda.org/conda-forge/linux-ppc64le/run_exports.json))
      - [X] Add to `regro/conda-forge-feedstock-check-solvable` - https://github.com/regro/conda-forge-feedstock-check-solvable/pull/17
    - [x] https://github.com/conda/conda-index/issues/102
- [x] Design a database schema and implementation that strikes a balance of performance and maintainability
  - [x] https://github.com/Quansight-Labs/czi-conda-forge-db/pull/5
- [ ] ~Devise am automated, provider-agnostic deployment strategy~ 
- [ ] ~Consolidate the existing data sources into the proposed database~
- [ ] ~Study how the existing bot infrastructure can benefit from the database to inform the next steps~

## 📅 Estimated completion

This task should be finished in the first [12 months](https://github.com/Quansight-Labs/czi-conda-forge-mgmt/milestone/2).

## ℹ️ References

- https://github.com/conda-forge/feedstock-outputs
- https://github.com/regro/cf-graph-countyfair
- https://github.com/regro/conda-suggest-conda-forge
- https://github.com/regro/libcfgraph
- https://github.com/regro/libcflib

**Comment by viniciusdc** [comment]
A quick follow-up on the last part of the previous answer: something I noticed so far is that if we're looking for faster querying of the JSON blobs directly, as in Marius's notebook linked above, having a single table containing all the artifacts might not be the best scenario because that could lead to intricate queries and could generate some burden.

So I've found two directions so far:

- One approach would be to create a separate table for the payloads, with a foreign key relationship to the artifacts table. This would allow us to query the payloads independently of the artifacts table, as explained in the previous answer.

- Another option would be to maintain the current scenario, but reduce the amount of data relationships in those JSON blobs by only including the necessary fields for querying. This would require some upfront analysis and data cleansing to determine which fields are truly necessary for querying, but it could simplify queries in the long run.

- Lastly, we could also consider a hybrid approach where we create a separate table for the most frequently queried fields in the JSON blobs, while still keeping the full JSON blobs in the artifacts table for more infrequent queries. -- though I think this would be quite unrelaistic as we possible always consume the whole table

Which approach we choose will depend on the specific needs of our application, but it's worth considering all options before making a decision.

**Comment by viniciusdc** [comment]
Hey there!

I was trying to figure out the best way to manage and query some [`import_to_pkg_maps`](https://github.com/regro/libcfgraph/tree/master/import_to_pkg_maps) files. I tested out two different approaches:

- Single table: one table with two columns - "package_name" (from the file name) and "payload" (the contents of the file)
![Single table - package_mapping](https://user-images.githubusercontent.com/51954708/232089723-28a1caae-585f-4d7e-aa7f-c8222ae1fe1e.png)

- Multi-table: two tables, "packages" and "package_contents", using a BTREE structure to store the data
Here's what I found:
![Multi table - package_contents](https://user-images.githubusercontent.com/51954708/232089769-7367369f-b4bb-45de-96c7-435870ad5d3e.png)
![Multi table - packages](https://user-images.githubusercontent.com/51954708/232089777-fc01e840-173b-4de0-8628-ba4216ce34d1.png)

### Here's what I found!
- Multi-table was better in terms of flexibility and efficiency
- The total size of the database was smaller (36MB for multi-table vs. 56MB for single table)
- Query execution time was faster for multi-table (47ms vs. 494ms for single table)
- To make sure both tables covered all the data, I created a parquet file following the structure of the multi-table approach
- The parquet file was smaller (9.6MB) and searching through it was faster (about 25ms using pandas)

Obs.: For each query, I inspected the values of the JSON blobs in the look for this element "access"

```python
to = time.time(); p.loc[p['field_value'] == 'access']; print(f"Took {(time.time() - to) * 1000} ms")
Took 24.831056594848633 ms
```

index | package_id | package_name | content_id | field_name | field_value
-- | -- | -- | -- | -- | --
294131 | 5221 | acces | 294132 | access | access
294132 | 5221 | acces | 294133 | access.access | access
294133 | 5221 | acces | 294134 | access.datasets | access
294134 | 5221 | acces | 294135 | access.fca | access
294135 | 5221 | acces | 294136 | access.helpers | access
294136 | 5221 | acces | 294137 | access.raam | access
294137 | 5221 | acces | 294138 | access.weights | access

**Comment by dhirschfeld** [comment]
As a `duckdb` fan I'm wondering if that wouldn't be a better choice.

**Comment by dhirschfeld** [comment]
Just popping up here to ask if it would be possible/feasible to have an `insert_timestamp` column for reproducibility so that you could query the database for data only entered before a specified timestamp. 

In that way you could ensure the result of your query would always be the same if you specified an `insert_timestamp <= '<some-date>'`. If data is updated after the fact (e.g. repodata patches) it can make it difficult to reproduce previous environments / analytics results.

**Comment by jaimergp** [comment]
Hi @dhirschfeld! We are not storing `repodata` stuff in this effort. AFAIK the `timestamp` field is rarely patched so it should work regardless. You can also get the unpatched repodata if you download `repodata_from_packages.json`, instead of the regular `repodata.json` :D

**Comment by dhirschfeld** [comment]
The point is you don't know when the repodata was patched. If you run an install command before the patch you'll get a different result than after.

For reproducibility you want to be able to say create an environment exactly the same as would have been created if I ran the command at `<specific-timestamp>`. AFAIK that's not possible with the current repodata/patches mechanism?  However, it would be easy if the data were stored in a database with the insert timestamp recorded.

...but maybe that's not what this issue is about, if so, apologies for the noise 😬!

**Comment by viniciusdc** [comment]
General feedback from some exploration of the data stored at feedstock outputs, I am confident that TRIE and K-tree-like structures generally work for scratch implementation that relies only on those mechanisms efficiently. If we move to SQL-based database, I am starting not to see the benefit of replicating this data disposition into the tables... as they usually don't transpose the same stability in the context of plain relational databases. ([excellent short post](https://www.baeldung.com/cs/storing-tree-in-rdb) on the subject)

Anyhow, I was able to test (a lot, but I will keep to two models here) two main approaches:
- Replicating the TRIE like structure, by using a child x parent_dir approach for keeping the hierarchical data disposition (example3.db) -- takes up to ~15min to populate all the tables, this can be improved

- Keeping a simple relational database implementation using only extra columns with the original relational_path stored. (test7.db) -- takes around 1 min to populate all the tables


In general, their sizes of then were on the same average:
```bash
$ du -sh /home/vcerutti/Conda-Forge/feedstock-outputs/outputs
98M     /home/vcerutti/Conda-Forge/feedstock-outputs/outputs

$ du -sh test7.py.sqlite
3,2M    test7.py.sqlite

$ du -sh example3.db
1,2M    example3.db
```
I still haven't explored much on how we would create the APIs for each example (though it's more straightforward to perform than using SQLalchemy schemas as the entry points), so I still can't say much about performance behavior when querying, as I was focused on reducing the amount of space required to store these data. 

I will follow up next week with some examples.

**Comment by jaimergp** [comment]
Oh, nice! I see there are a few interesting resources:

- https://github.com/mamba-org/quetz/blob/main/quetz/db_models.py
- https://github.com/mamba-org/quetz/tree/main/plugins/quetz_runexports
- https://github.com/mamba-org/quetz/tree/main/plugins/quetz_harvester
- https://github.com/mamba-org/quetz/tree/main/plugins/quetz_conda_suggest

**Comment by jaimergp** [comment]
Hi @viniciusdc, I am writing this here also for me. I just realized we had written down `conda-suggest-conda-forge` too as a potential database table (see references in 1st message).

The good thing is that we can generate those from the files-to-artifact map without an issue :D

**Comment by jaimergp** [comment]
Idea: we can serve the database from a small VM in open-gpu-server. It'd be easily redeployable. This can serve the files-to-artifacts search endpoint, I'd say?

**Comment by beckermr** [comment]
Def a good idea for testing. I am nervous about hosting services. We already have too much.
