### ISSUE TITLE
Migrate content from cf-infra-docs to conda-forge.org (maybe iteratively)

### ISSUE THREAD

**Issue by jaimergp** [Quansight-Labs/czi-conda-forge-mgmt#55]
* cf-infra-docs: https://github.com/Quansight-Labs/cf-infra-docs
* conda-forge's infrastructure: https://conda-forge.org/docs/maintainer/infrastructure/

Merge and mix

```[tasklist]
### Tasks
- [x] https://github.com/conda-forge/conda-forge.github.io/pull/2119
- [ ] https://github.com/conda-forge/conda-forge.github.io/pull/2139
- [ ] https://github.com/conda-forge/conda-forge.github.io/pull/2150
- [ ] https://github.com/conda-forge/conda-forge.github.io/pull/2158
```

**Comment by zklaus** [comment]
This is an overview of all the files to track handling.

# docs
- [x] getting-started.md (placeholder)
- [ ] index.md
- [x] miniforge.md (placeholder)
## fundamentals
- [ ] feedstocks.md
- [x] index.mdx (technical)
- [ ] life-cycle.md
- [x] publication.md (placeholder)
- [ ] staged-recipes.md
## howto
- [ ] index.md
## reference
- [ ] bot-commands.md
- [ ] feedstock-settings.md
- [ ] glossary.md
- [x] index.mdx (technical)
- [ ] pinnings.md
- [ ] runners.md
### infrastructure
- [ ] _events-triggers.md
- [ ] automated-maintenance.md
- [ ] diagrams.md
- [ ] feedstocks.md
- [x] index.mdx (technical)
- [ ] services.md
- [ ] staged-recipes.md
- [ ] tooling-data.md
- [ ] website.md
## advanced
- [ ] automation.md
- [x] index.mdx (technical)
- [x] security.md (placeholder)
## tutorials
- [x] index.mdx (technical)
- [x] submit-a-recipe.md (placeholder)

**Comment by jaimergp** [comment]
What are the checkboxes here for? 🤔

**Comment by zklaus** [comment]
> What are the checkboxes here for? 🤔

They get ticked when the file has been dealt with, meaning either determined to not need migration in its current form (e.g. purely technical or boilerplate contents), assigned to a different issue for tracking, or fully integrated into the migration branch at https://github.com/zklaus/conda-forge.github.io/tree/improve-infrastructure-documentation.

**Comment by jaimergp** [comment]
Ok, let's keep working on that branch until next week. Then we can start opening PRs, @goanpeca can help with the review(s) when time comes. To keep things scoped, let's open one PR per source (origin) page (e.g. "infrastructure docs revamp" discusses what happens with `maintainer/infrastructure.md`).

**Comment by zklaus** [comment]
We should also add https://github.com/regro/conda-forge-feedstock-check-solvable to the documented infrastructure.

**Comment by jaimergp** [comment]
Infra docs have migrated. Next in line: Diataxification of the docs via https://github.com/conda-forge/conda-forge.github.io/issues/2164
